version: '3.7'

services:
  postgres:
    container_name: postgres-bank
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASS}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:4.24
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    ports:
      - '5000:80'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_MQ_VHOST}
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
